testing out new arm64 builds & pulish

diff --git a/.github/actions/test-release/action.yaml b/.github/actions/test-release/action.yaml
--- a/.github/actions/test-release/action.yaml
+++ b/.github/actions/test-release/action.yaml
@@ -22,6 +22,9 @@ runs:
           curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-windows-amd64.exe -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "Linux" ]; then
+          if [ "${{ runner.arch }}" == "arm64" ]; then
+            curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-linux-arm64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
+          fi
           curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-linux-amd64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         chmod +x ./telepresence
