Workflow failure when curl execution is unsuccessful
Signed-off-by: shepz <gveschambre@datawire.io>

diff --git a/.github/actions/test-release/action.yaml b/.github/actions/test-release/action.yaml
--- a/.github/actions/test-release/action.yaml
+++ b/.github/actions/test-release/action.yaml
@@ -11,16 +11,16 @@ runs:
       shell: bash
       run: |
         if [ "${{ runner.os }}" = "macOS" ] && [ "${{ runner.arch }}" = "X64" ]; then
-          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-darwin-amd64 -o ./telepresence
+          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-darwin-amd64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "macOS" ] && [ "${{ runner.arch }}" = "ARM64" ]; then
-          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-darwin-arm64 -o ./telepresence
+          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-darwin-arm64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "Windows" ]; then
-          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-windows-amd64.exe -o ./telepresence
+          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-windows-amd64.exe -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "Linux" ]; then
-          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-linux-amd64 -o ./telepresence
+          curl -fL https://app.getambassador.io/download/tel2oss/releases/download/${{ inputs.release_version }}/telepresence-linux-amd64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         chmod +x ./telepresence
 
