Publish release images to ghrc.io instead of dockerhub
This commit changes the following:
1. Remove datawire/telepresence-internal-actions (not used anyway).
2. Publish release images to ghrc.io instead of docker.io.
3. Only use hosted github runners.

Signed-off-by: Thomas Hallgren <thomas@datawire.io>

diff --git a/.github/actions/test-release/action.yaml b/.github/actions/test-release/action.yaml
--- a/.github/actions/test-release/action.yaml
+++ b/.github/actions/test-release/action.yaml
@@ -12,22 +12,15 @@ runs:
         DOWNLOAD_URL: "https://app.getambassador.io/download/tel2oss/releases/download"
       shell: bash
       run: |
-        if [ "${{ runner.os }}" = "macOS" ] && [ "${{ runner.arch }}" = "X64" ]; then
-          curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-darwin-amd64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
-        fi
-        if [ "${{ runner.os }}" = "macOS" ] && [ "${{ runner.arch }}" = "ARM64" ]; then
-          curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-darwin-arm64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
+        if [ "${{ runner.os }}" = "macOS" ]; then
+          curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-darwin-${{ env.GOARCH }} -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "Windows" ]; then
-          curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-windows-amd64.zip -o ./telepresence.zip || { echo "Curl command failed" ; exit 1; }
+          curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-windows-${{ env.GOARCH }}.zip -o ./telepresence.zip || { echo "Curl command failed" ; exit 1; }
           unzip ./telepresence.zip || { echo "Unzip command failed" ; exit 1; }
         fi
         if [ "${{ runner.os }}" = "Linux" ]; then
-          if [ "${{ runner.arch }}" ==  "ARM64" ]; then
-            curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-linux-arm64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
-          else
-            curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-linux-amd64 -o ./telepresence || { echo "Curl command failed" ; exit 1; }
-          fi
+            curl -fL ${{ env.DOWNLOAD_URL }}/${{ inputs.release_version }}/telepresence-linux-${{ env.GOARCH }} -o ./telepresence || { echo "Curl command failed" ; exit 1; }
         fi
         chmod +x ./telepresence
 
